server:
  port: 8082
  tomcat:
    # http长连接时间为30s，默认为60s
    keep-alive-timeout: 30000
oj:
  swagger:
    title: 题目服务接口文档
    describe: 题目服务接口文档
    package: com.chencj.problem.controller
logging:
  level:
    com.chencj.problem: debug
    org.apache.tomcat: debug

# pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

